apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: courier-tracking
resources:
  - ../../base
patches:
  - path: frontend-nodeport.yaml
  - path: api-nodeport.yaml
images:
  - name: courier-tracking-api
    newTag: local
  - name: courier-tracking-frontend
    newTag: local