apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: courier
spec:
  ingressClassName: nginx
  rules:
    - host: courier.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: courier-frontend
                port:
                  number: 80