apiVersion: v1
kind: Secret
metadata:
  name: courier-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me-local-only
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: change-me-local-only
  JWT_SECRET: c2VjcmV0S2V5Rm9yRGV2ZWxvcG1lbnRPbmx5MzJieXRlcw==
  RABBITMQ_USER: courier
  RABBITMQ_PASSWORD: courier